Universidad/Controllers/TrazaNotasController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Universidad.Models;

namespace Universidad.Controllers
{
    public class TrazaNotasController : Controller
    {
        UniversidadEntities db = new UniversidadEntities();
        // GET: TrazaNotas
        public ActionResult Index()
        {
            var trazaNotas = db.TrazaNota;
            return View(trazaNotas);
        }
    }
}

Universidad/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Aplicación Universidad ASP.NET</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Aplicación Universidad", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Alumnos", "Index", "Alumnos")</li>
                    <li>@Html.ActionLink("Salones", "Index", "Salones")</li>
                    <li>@Html.ActionLink("Materias", "Index", "Materias")</li>
                    <li>@Html.ActionLink("Profesores", "Index", "Profesores")</li>
                    <li>@Html.ActionLink("Trazabilidad de notas", "Index", "TrazaNotas")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Aplicación Universidad</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>