Universidad/Models/Materias.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Universidad.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Materias
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Materias()
        {
            this.Alunmos_Materias = new HashSet<Alunmos_Materias>();
        }
    
        public int Id { get; set; }
        public string Nombre { get; set; }
        public int ProfesorId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Alunmos_Materias> Alunmos_Materias { get; set; }
        public virtual Profesores Profesores { get; set; }
    }
}

Universidad/Controllers/MateriasController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Universidad.Models;

namespace Universidad.Controllers
{
    public class MateriasController : Controller
    {
        UniversidadEntities db = new UniversidadEntities();
        // GET: Materias
        public ActionResult Index(string campo)
        {
            IEnumerable<Materias> materias;
            if (!string.IsNullOrEmpty(campo))
            {
                materias = db.Materias.Where(x => x.Nombre.ToLower().Trim().Contains(campo));
            }
            else
            {
                materias = db.Materias;
            }
            return View(materias);
        }

        // GET: Materias/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: Materias/Create
        public ActionResult Create()
        {
            List<Profesores> profesoresList = db.Profesores.ToList();
            var profesorList = profesoresList.Select(
                x => new
                {
                    ProfesorId = x.Id,
                    x.Nombre
                }
                );
            ViewBag.Profesores = new SelectList(profesorList, "ProfesorId", "Nombre");
            return View();
        }

        // POST: Materias/Create
        [HttpPost]
        public ActionResult Create(Materias collection)
        {
            try
            {
                db.Materias.Add(collection);
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: Materias/Edit/5
        public ActionResult Edit(int id)
        {
            List<Profesores> profesoresList = db.Profesores.ToList();
            var profesorList = profesoresList.Select(
                x => new
                {
                    ProfesorId = x.Id,
                    x.Nombre
                }
                );
            ViewBag.Profesores = new SelectList(profesorList, "ProfesorId", "Nombre");
            return View();
        }

        // POST: Materias/Edit/5
        [HttpPost]
        public ActionResult Edit(int id, Materias collection)
        {
            try
            {
                db.Entry(collection).State = System.Data.Entity.EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: Materias/Delete/5
        public ActionResult Delete(int id)
        {
            Materias materia = db.Materias.Find(id);
            return View(materia);
        }

        // POST: Materias/Delete/5
        [HttpPost]
        public ActionResult Delete(int id, Materias collection)
        {
            try
            {
                Materias materia = db.Materias.Find(id);

                db.Materias.Remove(materia);

                db.SaveChanges();

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }
    }
}

Universidad/Views/Materias/Create.cshtml
@model Universidad.Models.Materias

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Materias</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Nombre, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Nombre, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Nombre, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ProfesorId, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownListFor(model => model.ProfesorId, (SelectList)ViewBag.Profesores, new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.ProfesorId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Crear" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Regresar a la Lista", "Index")
</div>

Universidad/Views/Materias/Delete.cshtml
@model Universidad.Models.Materias

@{
    ViewBag.Title = "Delete";
}

<h2>Eliminar Materia</h2>

<h3>¿Está seguro de eliminar materia? Si tiene alumnos asociados no será posible eliminar. Por favor validar</h3>
<div>
    <h4>Materias</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Nombre)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Nombre)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ProfesorId)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ProfesorId)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Elimnar" class="btn btn-default" /> |
            @Html.ActionLink("Regresar a la Lista", "Index")
        </div>
    }
</div>

Universidad/Views/Materias/Edit.cshtml
@model Universidad.Models.Materias

@{
    ViewBag.Title = "Edit";
}

<h2>Editar Materia</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Materias</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id)

        <div class="form-group">
            @Html.LabelFor(model => model.Nombre, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Nombre, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Nombre, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.Label("Profesor", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownListFor(model => model.ProfesorId, (SelectList)ViewBag.Profesores, new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.ProfesorId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Guardar" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Regresar a la Lista", "Index")
</div>

Universidad/Views/Materias/Index.cshtml
@model IEnumerable<Universidad.Models.Materias>

@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

<p>
    @Html.ActionLink("Crear Nueva Materia", "Create")
</p>
<p>
    <input id="CampoBusqueda" type="text" class="form-control" placeholder="Ingresar Mínimo 4 Caracteres">
    <button id="BotonBusqueda" type="button" class="btn btn-secondary">Buscar Materia</button>
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Nombre)
        </th>
        <th>
            @Html.Display("Profesor")
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Nombre)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Profesores.Nombre)
        </td>
        <td>
            @Html.ActionLink("Editar Materia", "Edit", new { id=item.Id }) |
            @Html.ActionLink("Eliminar", "Delete", new { id=item.Id })
        </td>
    </tr>
}

</table>
@Scripts.Render("~/bundles/jquery")
<script>
    $(function () {
        $(document).on("click", "#BotonBusqueda", function (e) {
            var valor = $("#CampoBusqueda").val();
            if (valor.length < 4) 
                alert("Debe ingresar mínimo 4 caracteres");
            else
                window.location.href = '@Url.Action("Index", "Materias")'+'?campo='+valor;
        });
    });
    
</script>