Universidad/Models/Alumnos.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Universidad.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Alumnos
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Alumnos()
        {
            this.Alunmos_Materias = new HashSet<Alunmos_Materias>();
        }
    
        public long Cedula { get; set; }
        public System.DateTime FechaRegistro { get; set; }
        public string Nombre { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Alunmos_Materias> Alunmos_Materias { get; set; }
    }
}

Universidad/Controllers/AlumnosController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Universidad.Models;

namespace Universidad.Controllers
{
    public class AlumnosController : Controller
    {
        UniversidadEntities db = new UniversidadEntities();
        // GET: Alumnos
        public ActionResult Index(string cedula,string orden)
        {
            IEnumerable<Alumnos> alumnos;
            if (!string.IsNullOrEmpty(cedula))
            {
                alumnos = db.Alumnos.Where(x => x.Cedula.ToString().ToLower().Trim().Contains(cedula));
            }
            else
            {
                alumnos = db.Alumnos;
            }
            if(!string.IsNullOrEmpty(orden))
            {
                switch (orden)
                {
                    case "Cedula":
                        alumnos = db.Alumnos.OrderBy(x => x.Cedula);
                        break;
                    case "FechaRegistro":
                        alumnos = db.Alumnos.OrderBy(x => x.FechaRegistro);
                        break;
                    default:
                        alumnos = db.Alumnos;
                        break;
                }
            }
            return View(alumnos);
        }

        // GET: Alumnos/Details/5
        public ActionResult Details(int id)
        {
            
            var alumnosmaterias = db.Alumnos.Find(id).Alunmos_Materias;
            ViewBag.Cedula = id;
            return View(alumnosmaterias);
        }

        // GET: Alumnos/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Alumnos/Create
        [HttpPost]
        public ActionResult Create(Alumnos alumno)
        {
            try
            {
                alumno.FechaRegistro = DateTime.Now;
                db.Alumnos.Add(alumno);
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: Alumnos/Create
        public ActionResult CreateAlumnoMateria(int cedula)
        {
            List<Salones> SalonesList = db.Salones.ToList();
            var SalonPisoList = SalonesList.Select(
                x => new
                {
                    SalonId = x.Id,
                    Nombre = x.NumeroSalon + " - " + x.Piso
                }
                );
            ViewBag.Salones = new SelectList(SalonPisoList, "SalonId", "Nombre");

            List<Materias> MateriasList = db.Materias.ToList();
            var MateList = MateriasList.Select(
                x => new
                {
                    MateriaId = x.Id,
                    x.Nombre
                }
                );
            ViewBag.Materias = new SelectList(MateList, "MateriaId", "Nombre");

            Alunmos_Materias alumnoMateria = new Alunmos_Materias();
            alumnoMateria.Cedula = cedula;
            Alumnos alumno = db.Alumnos.Find(cedula);
            ViewBag.nombreEstudiante = alumno.Nombre;
            
            return View(alumnoMateria);
        }

        // POST: Alumnos/Create
        [HttpPost]
        public ActionResult CreateAlumnoMateria(Alunmos_Materias alumnomateria)
        {
            try
            {
                db.Alunmos_Materias.Add(alumnomateria);
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: Alumnos/Edit/5
        public ActionResult Edit(int id)
        {
            var alumno = db.Alumnos.Find(id);
            return View(alumno);
        }

        // POST: Alumnos/Edit/5
        [HttpPost]
        public ActionResult Edit(int id, Alumnos collection)
        {
            try
            {
                db.Entry(collection).State = System.Data.Entity.EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            catch (Exception e)
            {
                return View();
            }
        }

        // GET: Alumnos/Edit/5
        public ActionResult EditAlumnoMateria(int id)
        {
            List<Salones> SalonesList = db.Salones.ToList();
            var SalonPisoList = SalonesList.Select(
                x => new
                {
                    SalonId = x.Id,
                    Nombre = x.NumeroSalon + " - " + x.Piso
                }
                );
            ViewBag.Salones = new SelectList(SalonPisoList, "SalonId", "Nombre");

            List<Materias> MateriasList = db.Materias.ToList();
            var MateList = MateriasList.Select(
                x => new
                {
                    MateriaId = x.Id,
                    x.Nombre
                }
                );
            ViewBag.Materias = new SelectList(MateList, "MateriaId", "Nombre");
            var alumnoMateria = db.Alunmos_Materias.Find(id);
            return View(alumnoMateria);
        }

        // POST: Alumnos/Edit/5
        [HttpPost]
        public ActionResult EditAlumnoMateria(int id, Alunmos_Materias collection)
        {
            try
            {
                db.Entry(collection).State = System.Data.Entity.EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            catch (Exception e)
            {
                return View();
            }
        }

        // GET: Alumnos/Delete/5
        public ActionResult Delete(int id)
        {
            var alumno = db.Alumnos.Find(id);
            return View(alumno);
        }

        // POST: Alumnos/Delete/5
        [HttpPost]
        public ActionResult Delete(int id, Alumnos collection)
        {
            try
            {
                Alumnos alumno = db.Alumnos.Find(id);
                List<Alunmos_Materias> alunmos_Materias = db.Alunmos_Materias.Where(x => x.Cedula == id).ToList();

                if(alunmos_Materias != null)
                {
                    List<int> lstAlumnosMaterias = alunmos_Materias.Select(x => x.Id).ToList();
                    List<TrazaNota> trazaNotas = db.TrazaNota.Where(x => lstAlumnosMaterias.Contains(x.Alumnos_Materias_Id)).ToList();
                    if(trazaNotas != null)
                    {
                        db.TrazaNota.RemoveRange(trazaNotas);
                    }
                    db.Alunmos_Materias.RemoveRange(alunmos_Materias);
                }

                db.Alumnos.Remove(alumno);

                db.SaveChanges();

                return RedirectToAction("Index");
            }
            catch(Exception e)
            {
                return View();
            }
        }

        // GET: Alumnos/Delete/5
        public ActionResult DeleteAlumnoMateria(int id)
        {
            var alumnoMateria = db.Alunmos_Materias.Find(id);
            return View(alumnoMateria);
        }

        // POST: Alumnos/Delete/5
        [HttpPost]
        public ActionResult DeleteAlumnoMateria(int id, Alunmos_Materias collection)
        {
            try
            {
                Alunmos_Materias alumnoMateria = db.Alunmos_Materias.Find(id);

                List<TrazaNota> trazaNotas = db.TrazaNota.Where(x => x.Alumnos_Materias_Id == id).ToList();
                if (trazaNotas != null)
                {
                    db.TrazaNota.RemoveRange(trazaNotas);
                }
                db.Alunmos_Materias.Remove(alumnoMateria);

                db.SaveChanges();

                return RedirectToAction("Index");
            }
            catch (Exception e)
            {
                return View();
            }
        }

        // GET: Alumnos/EditNota/5
        public ActionResult EditNota(int id)
        {
            Alunmos_Materias alunmos_Materria = db.Alunmos_Materias.Find(id);
            return View(alunmos_Materria);
        }

        // POST: Alumnos/Delete/5
        [HttpPost]
        public ActionResult EditNota(int id, Alunmos_Materias collection)
        {
            try
            {
                int NotaOld = 0;
                int NotaNew = 0;
                Alunmos_Materias oldValue = db.Alunmos_Materias.AsNoTracking().FirstOrDefault(x => x.Id == id);

                int.TryParse(oldValue.Nota.ToString(), out NotaOld);
                int.TryParse(collection.Nota.ToString(), out NotaNew);

                TrazaNota trazaNota = new TrazaNota();
                trazaNota.ProfesorId = oldValue.Materias.ProfesorId;
                trazaNota.ValorAnterior = NotaOld;
                trazaNota.ValorNuevo = NotaNew;
                trazaNota.Alumnos_Materias_Id = collection.Id;

                db.TrazaNota.Add(trazaNota);
                db.Entry(collection).State = System.Data.Entity.EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }
    }
}

Universidad/Views/Alumnos/Create.cshtml
@model Universidad.Models.Alumnos

@{
    ViewBag.Title = "Create";
}

<h2>Crear Alumno</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Alumnos</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Cedula, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Cedula, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Cedula, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Nombre, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Nombre, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Nombre, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Crear" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Regresar a la Lista", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Universidad/Views/Alumnos/CreateAlumnoMateria.cshtml
@model Universidad.Models.Alunmos_Materias

@{
    ViewBag.Title = "CreateAlumnoMateria";
}

<h2>Asignar Nueva Materia</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Alunmos_Materias</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })

        <div class="form-group">
            @Html.LabelFor(model => model.Cedula, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DisplayFor(model => model.Cedula)
            </div>
        </div>

        <div class="form-group">
            @Html.Label("Nombre Alumno", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @ViewBag.nombreEstudiante
            </div>
        </div>

        <div class="form-group">
            @Html.Label("Materia", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownListFor(model => model.MateriaId, (SelectList)ViewBag.Materias, new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.MateriaId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.Label("Salón (Número Salón - Piso)", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownListFor(model => model.SalonId, (SelectList)ViewBag.Salones, new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.SalonId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Crear" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Universidad/Views/Alumnos/Delete.cshtml
@model Universidad.Models.Alumnos

@{
    ViewBag.Title = "Delete";
}

<h2>Eliminar Alumno</h2>

<h3>¿Está seguro de eliminar este Alumno?</h3>
@using (Html.BeginForm())
{
    <div>
        <h4>Alumnos</h4>
        <hr />
        <dl class="dl-horizontal">
            <dt>
                @Html.DisplayNameFor(model => model.Cedula)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Cedula)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.FechaRegistro)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.FechaRegistro)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.Nombre)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Nombre)
            </dd>

        </dl>


        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Elimnar" class="btn btn-default" /> |
            @Html.ActionLink("Regresar a la Lista", "Index")
        </div>
    </div>
}

Universidad/Views/Alumnos/DeleteAlumnoMateria.cshtml
@model Universidad.Models.Alunmos_Materias

@{
    ViewBag.Title = "DeleteAlumnoMateria";
}

<h2>Eliminar Materia a Alumno</h2>

<h3>¿Está seguro de eliminar esta materia?</h3>
<div>
    <h4>Alunmos_Materias</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Cedula)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Cedula)
        </dd>

        <dt>
            Materia
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Materias.Nombre)
        </dd>

        <dt>
            Salón (Número Salón - Piso)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Salones.NumeroSalon) - @Html.DisplayFor(model => model.Salones.Piso)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Nota)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Nota)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Eliminar" class="btn btn-default" /> |
            @Html.ActionLink("Regresar a la Lista", "Index")
        </div>
    }
</div>

Universidad/Views/Alumnos/Details.cshtml
@model IEnumerable<Universidad.Models.Alunmos_Materias>

@{
    ViewBag.Title = "Details";
}

<h2>Lista de Materias</h2>

<p>
    @Html.ActionLink("Asignar Nueva Materia", "CreateAlumnoMateria", new { cedula = ViewBag.Cedula })
</p>

<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Cedula)
        </th>
        <th>
            Nombre Alumno
        </th>
        <th>
            Materia
        </th>
        <th>
            Salon - Piso
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Nota)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Cedula)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Alumnos.Nombre)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Materias.Nombre)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Salones.NumeroSalon) - @Html.DisplayFor(modelItem => item.Salones.Piso)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Nota)
        </td>
        <td>
            @Html.ActionLink("Cambiar Nota", "EditNota", new { id = item.Id }) |
            @Html.ActionLink("Editar Materia", "EditAlumnoMateria", new { id = item.Id }) |
            @Html.ActionLink("Eiminar Materia", "DeleteAlumnoMateria", new { id = item.Id })
        </td>
    </tr>
}

</table>

Universidad/Views/Alumnos/Edit.cshtml
@model Universidad.Models.Alumnos

@{
    ViewBag.Title = "Edit";
}

<h2>Editar Alumno</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Alumnos</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Cedula, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Cedula, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Cedula, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.FechaRegistro, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DisplayFor(model => model.FechaRegistro)
            </div>
        </div>

        <div class="form-group" hidden>
            @Html.LabelFor(model => model.Nombre, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.FechaRegistro, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.FechaRegistro, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Nombre, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Nombre, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Nombre, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Guardar" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Regresar a la Lista", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Universidad/Views/Alumnos/EditAlumnoMateria.cshtml
@model Universidad.Models.Alunmos_Materias

@{
    ViewBag.Title = "EditAlumnoMateria";
}

<h2>Editar Asignacion de Materia</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Alumno - @Html.DisplayFor(model => model.Alumnos.Nombre)</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id)
        @Html.HiddenFor(model => model.Nota)
        @Html.HiddenFor(model => model.Cedula)

        <div class="form-group">
            @Html.LabelFor(model => model.Cedula, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DisplayFor(model => model.Cedula)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Nota, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DisplayFor(model => model.Nota)
            </div>
        </div>

        <div class="form-group">
            @Html.Label("Materia", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownListFor(model => model.MateriaId, (SelectList)ViewBag.Materias, new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.MateriaId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.Label("Salón (Número Salón - Piso)", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownListFor(model => model.SalonId, (SelectList)ViewBag.Salones, new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.SalonId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Guardar" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Regresar a la Lista", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Universidad/Views/Alumnos/EditNota.cshtml
@model Universidad.Models.Alunmos_Materias

@{
    ViewBag.Title = "EditNota";
}

<h2>Editar Nota</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

<div class="form-horizontal">
    <h4>Nota</h4>
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    @Html.HiddenFor(model => model.Id)
    @Html.HiddenFor(model => model.Cedula)
    @Html.HiddenFor(model => model.MateriaId)
    @Html.HiddenFor(model => model.SalonId)

    <div class="form-group">
        @Html.LabelFor(model => model.Cedula, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.DisplayFor(model => model.Cedula)
        </div>
    </div>

    <div class="form-group">
        @Html.Label("Estudiante", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.DisplayFor(model => model.Alumnos.Nombre)
        </div>
    </div>

    <div class="form-group">
        @Html.Label("Materia", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.DisplayFor(model => model.Materias.Nombre)
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Nota, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Nota, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Nota, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Guardar" class="btn btn-default" />
        </div>
    </div>
</div>
}

<div>
    @Html.ActionLink("Regresar a la Lista", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Universidad/Views/Alumnos/Index.cshtml
@model IEnumerable<Universidad.Models.Alumnos>

@{
    ViewBag.Title = "Index";
}

<h2>Lista de Alumnos</h2>
<p>
    <input id="CampoBusqueda" type="text" class="form-control" placeholder="Ingrese cédula">
    <button id="BotonBusqueda" type="button" class="btn btn-secondary">Buscar Alumno</button>
</p>
<p>
    @Html.ActionLink("Crear Nuevo Alumno", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.ActionLink("Cedula", "Index", new { orden = "Cedula" })
        </th>
        <th>
            @Html.ActionLink("Fecha de Registro", "Index", new { orden = "FechaRegistro" })
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Nombre)
        </th>
        <th>
            @Html.DisplayName("Promedio")
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Cedula)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.FechaRegistro)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Nombre)
            </td>
            <td>
                @{
                    double? promedio = item.Alunmos_Materias.Select(x => x.Nota).Average();
                    //double? promedio = 5;
                    var promedioString = promedio.ToString();
                }
                @promedioString
            </td>
            <td>
                @Html.ActionLink("Editar", "Edit", new { id = item.Cedula }) |
                @Html.ActionLink("Lista de materias", "Details", new { id = item.Cedula }) |
                @Html.ActionLink("Eliminar", "Delete", new { id = item.Cedula })
            </td>
        </tr>
    }

</table>
@Scripts.Render("~/bundles/jquery")
<script>
    $(function () {
        $(document).on("click", "#BotonBusqueda", function (e) {
            var valor = $("#CampoBusqueda").val();
            window.location.href = '@Url.Action("Index", "Alumnos")'+'?cedula='+valor;
        });
    });

</script>